/**
 * @brief The scanner takes one file's text as input and outputs the tokens.
 */

#ifndef INCLUDE_SCANNER_H_
#define INCLUDE_SCANNER_H_

#include <stddef.h>
#include "include/list.h"
#include "include/token.h"

/**
 * @brief The scanner converts one file's text to tokens.
 * 
 * @param text The text of the file to be scanned.
 * @param idx The scanner's index into the file's text.
 * @param loc The scanner's current location in the file's text, described as a
 * source_loc_t. This information could be recovered from text and idx, but
 * would need to be computed at O(n) cost to count the number of newlines, etc.
 * Every token generated by the scanner gets stamped with loc at the time of
 * creation. loc.filename may be NULL, indicating that the program text was read
 * as a literal string. This is usually done for testing.
 */
typedef struct scanner_t {
    char *text;
    size_t idx;
    source_loc_t loc;
} scanner_t;

/**
 * @brief Creates a new scanner from the program text as a string.
 */
scanner_t *scanner_create_from_text(char *text);

/**
 * @brief Creates a new scanner by opening the file and reading the contents.
 */
scanner_t *scanner_create_from_file(char *filename);

/**
 * @brief Frees all memory associated with the scanner.
 */
void scanner_destroy(scanner_t *scanner);

/**
 * @brief Returns the next token in the text, or TOK_EOF if all have been read.
 */
token_t *scanner_next(scanner_t *scanner);

/**
 * @brief Returns a list of all tokens in the text.
 * 
 * @deprecated Use scanner_next to retrieve tokens lazily. This function is only
 * preserved to support some unit tests, and will be removed in a future
 * release.
 */
list_t *scanner_all(scanner_t *scanner);

#endif  // INCLUDE_SCANNER_H_
